/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2016-07-20 03:48:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.secure.admin.jira.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class globalpermissions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/webwork.tld", Long.valueOf(1467871584000L));
    _jspx_dependants.put("/WEB-INF/tld/sitemesh-page.tld", Long.valueOf(1467871584000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005ftext_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005fparam_0026_005fname;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005fparam_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname.release();
    _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.release();
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname.release();
    _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>");
      if (_jspx_meth_ww_005ftext_005f0(_jspx_page_context))
        return;
      out.write("</title>\n");
      out.write("    <meta name=\"admin.active.section\" content=\"admin_users_menu/users_groups_configuration\"/>\n");
      out.write("    <meta name=\"admin.active.tab\" content=\"global_permissions\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      //  page:applyDecorator
      com.atlassian.jira.web.tags.JiraApplyDecoratorTag _jspx_th_page_005fapplyDecorator_005f0 = (com.atlassian.jira.web.tags.JiraApplyDecoratorTag) _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname.get(com.atlassian.jira.web.tags.JiraApplyDecoratorTag.class);
      _jspx_th_page_005fapplyDecorator_005f0.setPageContext(_jspx_page_context);
      _jspx_th_page_005fapplyDecorator_005f0.setParent(null);
      // /secure/admin/jira/views/globalpermissions.jsp(10,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_page_005fapplyDecorator_005f0.setName("jirapanel");
      int _jspx_eval_page_005fapplyDecorator_005f0 = _jspx_th_page_005fapplyDecorator_005f0.doStartTag();
      if (_jspx_eval_page_005fapplyDecorator_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_page_005fapplyDecorator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_page_005fapplyDecorator_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_page_005fapplyDecorator_005f0.doInitBody();
        }
        do {
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_page_005fparam_005f0(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_page_005fparam_005f1(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_page_005fparam_005f2(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return;
          out.write("\n");
          out.write("    <p>\n");
          out.write("    ");
          if (_jspx_meth_ww_005ftext_005f2(_jspx_th_page_005fapplyDecorator_005f0, _jspx_page_context))
            return;
          out.write("\n");
          out.write("    ");
          //  ww:text
          com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f3 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname.get(com.atlassian.jira.web.tags.TextTag.class);
          _jspx_th_ww_005ftext_005f3.setPageContext(_jspx_page_context);
          _jspx_th_ww_005ftext_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
          // /secure/admin/jira/views/globalpermissions.jsp(16,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_ww_005ftext_005f3.setName("'admin.globalpermissions.instruction'");
          int _jspx_eval_ww_005ftext_005f3 = _jspx_th_ww_005ftext_005f3.doStartTag();
          if (_jspx_eval_ww_005ftext_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_ww_005ftext_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.pushBody();
              _jspx_th_ww_005ftext_005f3.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
              _jspx_th_ww_005ftext_005f3.doInitBody();
            }
            do {
              out.write("\n");
              out.write("        ");
              //  ww:param
              webwork.view.taglib.ParamTag _jspx_th_ww_005fparam_005f0 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
              _jspx_th_ww_005fparam_005f0.setPageContext(_jspx_page_context);
              _jspx_th_ww_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005ftext_005f3);
              // /secure/admin/jira/views/globalpermissions.jsp(17,8) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_ww_005fparam_005f0.setName("'value0'");
              int _jspx_eval_ww_005fparam_005f0 = _jspx_th_ww_005fparam_005f0.doStartTag();
              if (_jspx_eval_ww_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspx_eval_ww_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.pushBody();
                  _jspx_th_ww_005fparam_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                  _jspx_th_ww_005fparam_005f0.doInitBody();
                }
                do {
                  out.write("<a href=\"");
                  out.print( request.getContextPath() );
                  out.write("/secure/admin/ViewPermissionSchemes.jspa\">");
                  int evalDoAfterBody = _jspx_th_ww_005fparam_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_ww_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_ww_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.reuse(_jspx_th_ww_005fparam_005f0);
                return;
              }
              _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.reuse(_jspx_th_ww_005fparam_005f0);
              out.write("\n");
              out.write("        ");
              if (_jspx_meth_ww_005fparam_005f1(_jspx_th_ww_005ftext_005f3, _jspx_page_context))
                return;
              out.write("\n");
              out.write("    ");
              int evalDoAfterBody = _jspx_th_ww_005ftext_005f3.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_ww_005ftext_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
            }
          }
          if (_jspx_th_ww_005ftext_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fww_005ftext_0026_005fname.reuse(_jspx_th_ww_005ftext_005f3);
            return;
          }
          _005fjspx_005ftagPool_005fww_005ftext_0026_005fname.reuse(_jspx_th_ww_005ftext_005f3);
          out.write("\n");
          out.write("    </p>\n");
          int evalDoAfterBody = _jspx_th_page_005fapplyDecorator_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_page_005fapplyDecorator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_page_005fapplyDecorator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname.reuse(_jspx_th_page_005fapplyDecorator_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fpage_005fapplyDecorator_0026_005fname.reuse(_jspx_th_page_005fapplyDecorator_005f0);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/includes/panels/permissionslist.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_ww_005ftext_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f0 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    _jspx_th_ww_005ftext_005f0.setPageContext(_jspx_page_context);
    _jspx_th_ww_005ftext_005f0.setParent(null);
    // /secure/admin/jira/views/globalpermissions.jsp(5,8) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ww_005ftext_005f0.setName("'admin.globalpermissions.global.permissions'");
    int _jspx_eval_ww_005ftext_005f0 = _jspx_th_ww_005ftext_005f0.doStartTag();
    if (_jspx_th_ww_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f0);
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f0 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    _jspx_th_page_005fparam_005f0.setPageContext(_jspx_page_context);
    _jspx_th_page_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
    // /secure/admin/jira/views/globalpermissions.jsp(11,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_page_005fparam_005f0.setName("title");
    int _jspx_eval_page_005fparam_005f0 = _jspx_th_page_005fparam_005f0.doStartTag();
    if (_jspx_eval_page_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_page_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_page_005fparam_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_page_005fparam_005f0.doInitBody();
      }
      do {
        if (_jspx_meth_ww_005ftext_005f1(_jspx_th_page_005fparam_005f0, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_page_005fparam_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_page_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_page_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f0);
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fparam_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f1 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    _jspx_th_ww_005ftext_005f1.setPageContext(_jspx_page_context);
    _jspx_th_ww_005ftext_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fparam_005f0);
    // /secure/admin/jira/views/globalpermissions.jsp(11,29) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ww_005ftext_005f1.setName("'admin.globalpermissions.global.permissions'");
    int _jspx_eval_ww_005ftext_005f1 = _jspx_th_ww_005ftext_005f1.doStartTag();
    if (_jspx_th_ww_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f1);
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f1 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    _jspx_th_page_005fparam_005f1.setPageContext(_jspx_page_context);
    _jspx_th_page_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
    // /secure/admin/jira/views/globalpermissions.jsp(12,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_page_005fparam_005f1.setName("width");
    int _jspx_eval_page_005fparam_005f1 = _jspx_th_page_005fparam_005f1.doStartTag();
    if (_jspx_eval_page_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_page_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_page_005fparam_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_page_005fparam_005f1.doInitBody();
      }
      do {
        out.write("100%");
        int evalDoAfterBody = _jspx_th_page_005fparam_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_page_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_page_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f1);
    return false;
  }

  private boolean _jspx_meth_page_005fparam_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  page:param
    com.opensymphony.module.sitemesh.taglib.page.ParamTag _jspx_th_page_005fparam_005f2 = (com.opensymphony.module.sitemesh.taglib.page.ParamTag) _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.get(com.opensymphony.module.sitemesh.taglib.page.ParamTag.class);
    _jspx_th_page_005fparam_005f2.setPageContext(_jspx_page_context);
    _jspx_th_page_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
    // /secure/admin/jira/views/globalpermissions.jsp(13,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_page_005fparam_005f2.setName("helpURL");
    int _jspx_eval_page_005fparam_005f2 = _jspx_th_page_005fparam_005f2.doStartTag();
    if (_jspx_eval_page_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_page_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_page_005fparam_005f2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_page_005fparam_005f2.doInitBody();
      }
      do {
        out.write("global_permissions");
        int evalDoAfterBody = _jspx_th_page_005fparam_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_page_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_page_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fpage_005fparam_0026_005fname.reuse(_jspx_th_page_005fparam_005f2);
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_page_005fapplyDecorator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f2 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    _jspx_th_ww_005ftext_005f2.setPageContext(_jspx_page_context);
    _jspx_th_ww_005ftext_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_page_005fapplyDecorator_005f0);
    // /secure/admin/jira/views/globalpermissions.jsp(15,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ww_005ftext_005f2.setName("'admin.globalpermissions.description'");
    int _jspx_eval_ww_005ftext_005f2 = _jspx_th_ww_005ftext_005f2.doStartTag();
    if (_jspx_th_ww_005ftext_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f2);
    return false;
  }

  private boolean _jspx_meth_ww_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_ww_005ftext_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:param
    webwork.view.taglib.ParamTag _jspx_th_ww_005fparam_005f1 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
    _jspx_th_ww_005fparam_005f1.setPageContext(_jspx_page_context);
    _jspx_th_ww_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ww_005ftext_005f3);
    // /secure/admin/jira/views/globalpermissions.jsp(18,8) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ww_005fparam_005f1.setName("'value1'");
    int _jspx_eval_ww_005fparam_005f1 = _jspx_th_ww_005fparam_005f1.doStartTag();
    if (_jspx_eval_ww_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_ww_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_ww_005fparam_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_ww_005fparam_005f1.doInitBody();
      }
      do {
        out.write("</a>");
        int evalDoAfterBody = _jspx_th_ww_005fparam_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_ww_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_ww_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.reuse(_jspx_th_ww_005fparam_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fww_005fparam_0026_005fname.reuse(_jspx_th_ww_005fparam_005f1);
    return false;
  }
}
