/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2016-07-19 00:47:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.secure.admin.views.workflow;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class editworkflowscheme_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/tld/webwork.tld", Long.valueOf(1467871584000L));
    _jspx_dependants.put("/WEB-INF/tld/atlassian-jira-tags.tld", Long.valueOf(1467871584000L));
    _jspx_dependants.put("/WEB-INF/tld/sitemesh-page.tld", Long.valueOf(1467871584000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjira_005fweb_002dresource_002drequire_0026_005fmodules_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjira_005fweb_002dresource_002drequire_0026_005fmodules_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjira_005fweb_002dresource_002drequire_0026_005fmodules_005fnobody.release();
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    ");
      if (_jspx_meth_jira_005fweb_002dresource_002drequire_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <title>");
      if (_jspx_meth_ww_005ftext_005f0(_jspx_page_context))
        return;
      out.write("</title>\n");
      out.write("    <meta name=\"admin.active.section\" content=\"admin_issues_menu/element_options_section/workflows_section\"/>\n");
      out.write("    <meta name=\"admin.active.tab\" content=\"workflow_schemes\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div id=\"workflowscheme-editor\" class=\"workflowscheme-editor-loading\"></div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jira_005fweb_002dresource_002drequire_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jira:web-resource-require
    com.atlassian.jira.web.tags.WebResourceRequireTag _jspx_th_jira_005fweb_002dresource_002drequire_005f0 = (com.atlassian.jira.web.tags.WebResourceRequireTag) _005fjspx_005ftagPool_005fjira_005fweb_002dresource_002drequire_0026_005fmodules_005fnobody.get(com.atlassian.jira.web.tags.WebResourceRequireTag.class);
    _jspx_th_jira_005fweb_002dresource_002drequire_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jira_005fweb_002dresource_002drequire_005f0.setParent(null);
    // /secure/admin/views/workflow/editworkflowscheme.jsp(9,4) name = modules type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jira_005fweb_002dresource_002drequire_005f0.setModules("com.atlassian.jira.jira-project-config-plugin:edit-workflow-scheme");
    int _jspx_eval_jira_005fweb_002dresource_002drequire_005f0 = _jspx_th_jira_005fweb_002dresource_002drequire_005f0.doStartTag();
    if (_jspx_th_jira_005fweb_002dresource_002drequire_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjira_005fweb_002dresource_002drequire_0026_005fmodules_005fnobody.reuse(_jspx_th_jira_005fweb_002dresource_002drequire_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjira_005fweb_002dresource_002drequire_0026_005fmodules_005fnobody.reuse(_jspx_th_jira_005fweb_002dresource_002drequire_005f0);
    return false;
  }

  private boolean _jspx_meth_ww_005ftext_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ww:text
    com.atlassian.jira.web.tags.TextTag _jspx_th_ww_005ftext_005f0 = (com.atlassian.jira.web.tags.TextTag) _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.get(com.atlassian.jira.web.tags.TextTag.class);
    _jspx_th_ww_005ftext_005f0.setPageContext(_jspx_page_context);
    _jspx_th_ww_005ftext_005f0.setParent(null);
    // /secure/admin/views/workflow/editworkflowscheme.jsp(10,11) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ww_005ftext_005f0.setName("'admin.schemes.workflow.edit.title'");
    int _jspx_eval_ww_005ftext_005f0 = _jspx_th_ww_005ftext_005f0.doStartTag();
    if (_jspx_th_ww_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fww_005ftext_0026_005fname_005fnobody.reuse(_jspx_th_ww_005ftext_005f0);
    return false;
  }
}
